[package]
name = "scale_signature"
version = "0.0.1"
edition = "2021"
exclude = [
    "**/*.go",
    "**/*.templ",
    "go.mod",
    "go.sum",
]

[dependencies]

[lib]
crate-type = ["cdylib"]
path = "signature.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

