[package]
name = "scale_signature"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["cdylib"]
path = "signature.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
